### ISSUE TITLE
Front End/UI

### ISSUE THREAD

**Issue by medricr** [medricr/Group_Project_2#4]
##TODO 
- [x] Create a homepage with a title, description and links to 
- [x] Create submit form where the user can enter all fields, which will be required
- [x] A display page which will show all of the recipes that have been entered in the database

**Comment by YaroslavPetsenyuk** [comment]
Done with the Home Page and the Form Page
