### ISSUE TITLE
Back End - Routes / Database

### ISSUE THREAD

**Issue by medricr** [medricr/Group_Project_2#5]
##TODO
- [ ] Create a database which will hold all of the recipes needed
- [ ] Create a server which will link the database to what the user sees
- [ ] Create routes for manipulating the database and returning that information to the user
